---
name: top_level_group_creation_enabled
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56360
rollout_issue_url:
milestone: '13.10'
type: ops
group: group::access
default_enabled: true
