---
name: vulnerability_management_survey
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56620
rollout_issue_url:
milestone: '13.11'
type: ops
group: group::threat insights
default_enabled: false
