---
name: linear_user_membership_groups
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/68842
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/339432
milestone: '14.3'
type: development
group: group::access
default_enabled: false
