---
name: linear_groups_template_finder_extended_group_search
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/68936
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/339439
milestone: '14.3'
type: development
group: group::access
default_enabled: false
