description: Invite members to group
category: GroupsController
action: invite_members
label_description: The string "new_group_form"
property_description:
value_description:
extra_properties:
identifiers:
product_section: growth
product_stage: growth
product_group: expansion
product_category:
milestone: "13.8"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/48794
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
