---
name: calendly_invite_link
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61146
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330340
milestone: '13.12'
type: development
group: group::activation
default_enabled: false
