---
name: ci_minutes_use_notification_level
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/69059
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/339324
milestone: '14.3'
type: development
group: group::pipeline execution
default_enabled: false
