---
name: disable_merge_trains
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/24844
rollout_issue_url: 
milestone: '12.8'
type: development
group: group::pipeline execution
default_enabled: false
