---
name: geo_secondary_proxy
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56297
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/325732
milestone: '13.11'
type: development
group: group::geo
default_enabled: false
