---
name: iteration_board_lists
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49688
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/250479
milestone: '13.7'
type: development
group: group::project management
default_enabled: true
