---
name: saas_user_caps
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66264
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/336251
milestone: '14.1'
type: development
group: group::utilization
default_enabled: false
