---
name: scan_result_policy
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/70631
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/339338
milestone: '14.4'
type: development
group: group::container security
default_enabled: false
