---
key_path: usage_activity_by_stage_monthly.enablement.geo_node_usage
name: geo_node_usage
description: Usage data for geo nodes
product_section: enablement
product_stage: enablement
product_group: group::geo
product_category: geo_replication
value_type: object
status: active
milestone: "14.3"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/70062
time_frame: all
data_source: database
data_category: optional
performance_indicator_type: []
distribution:
- ee
tier:
- premium
- ultimate
value_json_schema: "ee/config/metrics/object_schemas/geo_node_usage.json"
