---
name: lower_relation_max_count_limit
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/69620
rollout_issue_url:
milestone: '14.3'
type: ops
group: group::verify
default_enabled: false
