---
key_path: usage_activity_by_stage.secure.user_cluster_image_scanning_scans
description: Number of users who have run a Cluster image scan
product_section: sec
product_stage: protect
product_group: group::container security
value_type: number
status: deprecated
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49444
time_frame: all
data_source: database
data_category: Optional
distribution:
  - ee
tier:
  - ultimate
